### ISSUE TITLE
Running in production depends on a dev dependency?

### ISSUE THREAD

**Issue by wadim** [rocjs/roc-package-web-app-react#28]
The following code:

```
$ roc start
```

does not produce warnings.

But the following code:

```
$ npm prune --production
$ roc start
```

does produce warnings:

```
Found a local version of Roc, will use that over the global one. 

  Warning    Roc Extension Loading Failed

  Failed to load Roc package named roc-package-web-app-react-dev.
  Make sure you have it installed. Try running: npm install --save roc-package-web-app-react-dev

  Warning    Roc Extension Loading Failed

  Failed to load Roc plugin named roc-plugin-style-less.
  Make sure you have it installed. Try running: npm install --save roc-plugin-style-less

  Warning    Configuration

  There was a mismatch in the application configuration structure, make sure this is correct.
  Did not understand settings.build.path
  Did not understand settings.build.reduxMiddlewares
  Did not understand settings.build.koaMiddlewares
  Did not understand settings.build.style.modules
  Did not understand settings.build.resources
  Did not understand settings.build.reducers
  Did not understand settings.build.routes
  Did not understand settings.dev.browsersync.open

Roc runtime has been initialized.
Starting Roc application…
  roc:server Server started on port 3000 (HTTP) and served from / +0ms
```

I would expect removing the `devDependencies` would not have any consequences for the application.

As far as I understand, the warnings indicate that:
- the application in production depends on the `roc-package-web-app-react-dev` package
- the application in production depends on the `roc-plugin-style-less` package
- roc was not able to find my configuration

roc is also suggesting I `npm install --save` both packages.

Aren't these packages development packages which are only needed during the build step and no longer needed in production?

**Comment by dlmr** [comment]
Thanks for the question! 

They are not needed.

The thing that is happening here is that Roc scans your `package.json` and tries to load all of the extensions it can find in it and fails since they are not installed. The warning about the mismatch in configuration is because no extension have registered those settings, since they was not loaded because they where not installed. 

So the problem here is that Roc tries to be nice and tell the user what is happening but as you have noted this can be misunderstood when running in production. We should try to come up with a smart way to not show this when running in production, maybe we can hook into npm in some way?

I will create an issue about this in the main repo soon that follows this up.

**Comment by dlmr** [comment]
There is a workaround for this when running in production that I should mention.

You can specify what configuration file that you want to load and using this we could create a configuration file for production and one for development. Since the configuration files are just JavaScript you could also combine them like this:

``` js
// Production
// roc.config.production.js
module.exports = {
  settings: {
    runtime: {}
  },
  packages: ['roc-package-web-app-react']
};
```

``` js
// Development
// roc.config.js
module.exports = Object.assign({}, require('./roc.config.js'), {
  // …  
  packages: [] // To let Roc get all from our package.json
};
```

Now we can start in production like this:

``` bash
$ roc start --config roc.config.production.js
```

_This will change a little in the next version._
