### ISSUE TITLE
How to use with New Relic?

### ISSUE THREAD

**Issue by wadim** [rocjs/roc-package-web-app-react#52]
New Relic's instructions say:

> Make this the first line of your app's startup script:
> `require('newrelic');`

However, in `roc-package-web-app-react`, the "app's startup script" is hidden from mere application developers and located somewhere in `roc` internals.

I gave this problem two attempts:

1. First I tried including the module in `routes/index.js`.
2. Then I tried including it in a file which defines a `koa` middleware.

Both attempts produce the following warning from New Relic:

> The newrelic module must be the first module required.
> The following modules were required before newrelic and are not being instrumented:
> 	connect

Also, since my app is a universal JS app, I need to access to the result of the `require('newrelic')` call to instrument the client-side app in New Relic's way of instrumenting the client-side which is using a call like the one below

> `newrelic.getBrowserTimingHeader()`

which produces `script` tags which need to be manually injected by my application to the HTML output.

**Comment by dlmr** [comment]
### `require('newrelic')`
I think you will need to start the application without the use of the CLI here to make this possible. 

#### Alternative 1
Create a [custom entry point](https://github.com/rocjs/roc/blob/master/docs/Runtime.md#using-a-custom-entry-point).

```js
require('newrelic');
require('roc/runtime/register');
require('./build/server/app.js');
```

With this we can now start the application using Node.

#### Alternative 2
Use [`-r`](https://nodejs.org/api/cli.html#cli_r_require_module) in Node and [start directly manually](https://github.com/rocjs/roc/blob/master/docs/Runtime.md#start-the-application-using-the-command-line-script-manually).

```
node -r newrelic node_modules/.bin/roc start
```

### `newrelic.getBrowserTimingHeader()`
Getting the `newrelic.getBrowserTimingHeader()` into the template is a little more tricky since we do not offer a simple way of doing that currently. But we can use an undocumented API to get this working _(this will most likely change in the future)_.

We will start with creating a file under `src/template-values.js`, this is connected with `settings.build. templateValues` in Roc. This file is expected to export a function that returns an object that is exposed to the template as `custom`.

```js
import newrelic from 'newrelic';

// Will be called for each render
export default function custom(koaState, rocSettings, reduxState) {
  return {
    newrelic: newrelic.getBrowserTimingHeader(),
  };
}
```

Now we can take over the template file and use this new data.

```nunjucks
<!DOCTYPE html>
<html {{ head.htmlAttributes | safe }}>
  <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
          
        {# Add New Relic integration #}
        {{ custom.newrelic | safe }}

        {{ head.title.toString() | safe }}
        {{ head.meta.toString() | safe }}
        {{ head.link.toString() | safe }}
        {{ head.base.toString() | safe }}
        {{ head.script.toString() | safe }}
        {{ head.style.toString() | safe }}

        {% if dist %}
        <link rel="stylesheet" href="{{ styleName }}">
        {% endif %}
    </head>
    {% if custom.bodyClass %}
    <body class="{{ custom.bodyClass | safe }}">
    {% else %}
    <body>
    {% endif %}
        <div id="application">{{ content | safe }}</div>

        <script>window.ROC_CONFIG = {{ serializedRocConfig | safe }}</script>
        <script>window.APP_CONFIG = {{ serializedAppConfig | safe }}</script>
        <script>window.FLUX_STATE = {{ fluxState | safe }}</script>
        <script>window.__REDIAL_PROPS__ = {{ redialProps | safe }}</script>

        <script src="{{ bundleName }}"></script>
    </body>
</html>
```

Now we should have everything up and running.

Please get back to me if there is any problems making this work since I have not tested this myself.

**Comment by wadim** [comment]
Thanks @dlmr! I will test this and get back to you.

**Comment by wadim** [comment]
@dlmr: I have an application which uses a custom entry point. How can I launch it in development mode so that the custom entry point is run too?
