### ISSUE TITLE
beforeTransition hooks triggered after transition?

### ISSUE THREAD

**Issue by wadim** [rocjs/roc-package-web-app-react#84]
## Expectation

I expect `beforeTransition` hooks to be executed before a component is rendered and to block rendering of the component until the promise they return is resolved.

## Reality

`beforeTransition` hooks are executed after the component is rendered and they do not block rendering of the component.

## Reproducible example

To create a reproducible example I forked this repo and added two `console.log` statements to the "complex" example:
 - one to the `render` function which prints `render`
 - one to a `beforeTransition` hook which prints `fetch`

On the server side, the hooks are executed in the order I would expect (`fetch` before `render`):

<img width="120" alt="server" src="https://user-images.githubusercontent.com/941978/31711050-357292d6-b3f7-11e7-8c46-1aac4385072d.png">

However, on the client side, `render` is called (twice) before `fetch`:

<img width="249" alt="client" src="https://user-images.githubusercontent.com/941978/31711049-3557a07a-b3f7-11e7-9310-c57c2c7d5b2d.png">

Link to the fork: https://github.com/wadim/roc-package-web-app-react/tree/master/examples/complex

**Comment by wadim** [comment]
It also seems it is not possible to use the `loading` property in `render` (provided by [react-router-redial](https://github.com/dlmr/react-router-redial)) to determine whether the `fetch` hook has run:

<img width="251" alt="client-with-loading" src="https://user-images.githubusercontent.com/941978/31713096-6f014c94-b3fd-11e7-8834-aa7d0a3284e1.png">

**Comment by wadim** [comment]
@dlmr Is this a bug or am I misunderstanding the expected behaviour?

**Comment by dlmr** [comment]
The example you showed above only happen when triggering redial for a component that already is visible/rendered. The reason for this is that the component already is present in our component tree and redial will not remove it or prevent it from rendering. What it will do however is prevent it to be shown when we transition to it. If you want to hide a component when the loading happens you can implement that in your application, or implement a `shouldComponentUpdate` method.

The first render is React mounting on the client into the server side rendering, then redial is triggered and we renders again because we now have loading set to `true`. The when we finished the fetching we render again with loading `false`. 

So this is working as expected as of now, even if it might be a little confusing. You will see what you want if you for example load the application on another page and then click the link to go to _Home_.
